### ISSUE TITLE
`tsx` doesn't recognize environment variables

### ISSUE THREAD

**Issue by erikash** [t3-oss/t3-env#167]
I created a db migrator script similar to the recommendations here:
https://create.t3.gg/en/usage/prisma/#seeding-your-database

I'm trying to execute the script and the t3-env doesn't seem to load the `.env` file.

Steps to reproduce:
1. `create-t3-app` with Drizzle and App Router.
2. Add the following:

`src/server/db/migrator.ts` is:
```
import { migrate } from "drizzle-orm/neon-http/migrator";
import { db } from "~/server/db/index";

await migrate(db, { migrationsFolder: "src/server/db/drizzle" });
```

`package.json` scripts are:
```
  "scripts": {
    ...
    "migrate": "tsx ./src/server/db/migrator.ts"
  },
```

3. Run `pnpm run migrate`:
```
❌ Invalid environment variables: {
  DATABASE_URL: [ 'Required' ],
  DISCORD_CLIENT_ID: [ 'Required' ],
  DISCORD_CLIENT_SECRET: [ 'Required' ]
}
/Users/erikashepa/Projects/budget/node_modules/.pnpm/@t3-oss+env-nextjs@0.7.1_typescript@5.1.6_zod@3.22.4/node_modules/@t3-oss/core/index.ts:217
      throw new Error("Invalid environment variables");
            ^


Error: Invalid environment variables
    at error (/Users/erikashepa/Projects/budget/node_modules/.pnpm/@t3-oss+env-nextjs@0.7.1_typescript@5.1.6_zod@3.22.4/node_modules/@t3-oss/core/index.ts:217:13)
    at b (/Users/erikashepa/Projects/budget/node_modules/.pnpm/@t3-oss+env-nextjs@0.7.1_typescript@5.1.6_zod@3.22.4/node_modules/@t3-oss/core/index.ts:229:12)
    at P (/Users/erikashepa/Projects/budget/node_modules/.pnpm/@t3-oss+env-nextjs@0.7.1_typescript@5.1.6_zod@3.22.4/node_modules/@t3-oss/env-nextjs/index.ts:73:10)
    at file:///Users/erikashepa/Projects/budget/src/env.js:4:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.1
```

**Comment by erikash** [comment]
@Admiral-Enigma can confirm that `import "dotenv/config" solve this :)

I tried to import `dotenv` in other ways and it didn't help.. kudos :)

```
import "dotenv/config";

import { migrate } from "drizzle-orm/neon-http/migrator";
import { db } from "~/server/db/index";

await migrate(db, { migrationsFolder: "src/server/db/drizzle" });

```

**Comment by deadcoder0904** [comment]
you can use `tsx` with [node v20's `--env-file`](https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs) feature like:

```json
    "db:seed": "node --import tsx --env-file .env ./seed/insert.ts",
```

i've [myself used it](https://github.com/deadcoder0904/next-14-lucia-v3-sqlite-drizzle-conform-zod-email-verification-otp-server-actions/blob/main/package.json#L14) in my project.
