### ISSUE TITLE
Invalid environment variables in CI environment running tests

### ISSUE THREAD

**Issue by vertex** [t3-oss/t3-env#62]
Once it got to my CI, the validation failed -- and whats weird is it ran successfully locally.  Would be nice if it failed nicely in a CI environment, but also my test shouldn't have accessed a env variable.

```
$ npm test
> /project@1.0.17 test
> mocha --require ts-node/register --timeout 100000 --require ./dist/test-setup.js './src/**/*.spec.js' './src/**/*.spec.ts'
❌ Invalid environment variables: {
  ...
}
Error: Invalid environment variables
    at /project/node_modules/@t3-oss/env-core/index.ts:155:1
    at g (/project/node_modules/@t3-oss/env-core/index.ts:155:1)
    at Object.<anonymous> (/project/src/env.ts:5:29)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .ts] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/src/victorops/api.ts:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .ts] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/src/data/Team.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .ts] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/src/consts.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .js] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/src/puppet/consts.js:39:6)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .js] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/src/puppet/test/controller.spec.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .js] (/project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/project/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async Object.exports.requireOrImport (/project/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async Object.exports.loadFilesAsync (/project/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/project/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/project/node_modules/mocha/lib/cli/run.js:370:5)
```

Anyways, for now I did a 
```
export const env = process.env.IS_CI
	? process.env
	: createEnv({});
```
Thoughts?

**Comment by intagaming** [comment]
There's this line in your stacktrace: `at Object.<anonymous> (/project/src/victorops/api.ts:14:1)`, which means your CI did actually touched this file, which imported the `env.ts` file, which triggered the env validation. Maybe you didn't actually call any function inside `api.ts` that accesses an environment variable from `env.ts`, but `api.ts` is importing `env.ts` so it is assumed by default that `api.ts` always uses `env.ts`.

Now, I think the problem is that either the test should be skipping the validation of some environment variables that are not present at the time that the test runs, or it should not skip at all because `api.ts` indeed needs some variables in order to function properly, and that depends on your test's purpose. I'm assuming it's the latter because your specified `const env =` to be `process.env`; otherwise you would have put it as `{}` if your test doesn't use env vars at all. So you should validate your envs. The fact that you can validate locally but failed to run on CI environment means that your CI environment is not "identically identical" to your local environment. If it's just the same command running locally as well as CI, then it's almost always the environment variables that are the culprit.

**Comment by juliusmarminge** [comment]
@intagaming is correct. Your tests should reflect the real would. If they dont require them, use dummies, or use the `skipValidation` option to omit them.

You can also make more complex schemas that only makes a var required in certain environments (see NEXTAUTH_URL and NEXTAUTH_SECRET in create-t3-app for examples)
