### ISSUE TITLE
Allow exit on failure kind of behaviour

### ISSUE THREAD

**Issue by Nsttt** [t3-oss/t3-env#88]
When using t3-env on a container scenario, it will be useful to force a `process.exit` when invalid variables are detected. 

This is due to container environments usually relying on different containers state reports to check wether it is working properly or it should be rolled back. 

This can probably be implemented as a optional flag defaulted to false like `exitOnFailureValidation`.

The current behaviour is simply a throw via console.

```
❯ docker run -p 3000:3000 t3-test-app
Listening on port 3000 url: http://e1699a2062d6:3000
❌ Invalid environment variables: {
  DATABASE_URL: [ 'Required' ],
  NEXTAUTH_SECRET: [ 'Required' ],
  NEXTAUTH_URL: [ 'Required' ]
}
Error: Invalid environment variables
    at f (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:386)
    at l (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:576)
    at C (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:749)
    at /app/.next/server/chunks/115.js:98:74
Error: Invalid environment variables
    at f (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:386)
    at l (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:576)
    at C (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:749)
    at /app/.next/server/chunks/115.js:98:74
Error: Invalid environment variables
    at f (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:386)
    at l (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:576)
    at C (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:749)
    at /app/.next/server/chunks/115.js:98:74
Error: Invalid environment variables
    at f (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:386)
    at l (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:576)
    at C (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:749)
    at /app/.next/server/chunks/115.js:98:74
Error: Invalid environment variables
    at f (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:386)
    at l (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:576)
    at C (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:749)
    at /app/.next/server/chunks/115.js:98:74
Error: Invalid environment variables
    at f (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:386)
    at l (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:576)
    at C (file:///app/node_modules/.pnpm/@t3-oss+env-nextjs@0.3.1_typescript@5.0.4_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:749)
    at /app/.next/server/chunks/115.js:98:74```

**Comment by Nsttt** [comment]
We could also leave a note in the docs to opt for.

```ts
      onValidationError: () => {
        process.exit(1);
      },
```

**Comment by chungweileong94** [comment]
Sounds cool, but have you try that by overriding the `onValidationError` option?

**Comment by juliusmarminge** [comment]
You have full control over what hoppens on error: https://env.t3.gg/docs/customization

**Comment by juliusmarminge** [comment]
Needs a repro if `onValidationError` doesn't work
